/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.SqlExecutorBooleanValue;
import org.wso2.developerstudio.eclipse.gmf.esb.SqlExecutorConnectionType;
import org.wso2.developerstudio.eclipse.gmf.esb.SqlExecutorDatasourceType;
import org.wso2.developerstudio.eclipse.gmf.esb.SqlExecutorIsolationLevel;
import org.wso2.developerstudio.eclipse.gmf.esb.SqlStatement;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.AbstractSqlExecutorMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractSqlExecutorMediatorValidator {
	boolean validate();

	boolean validateConnectionType(SqlExecutorConnectionType value);
	boolean validateConnectionDsType(SqlExecutorDatasourceType value);
	boolean validateConnectionDbDriver(String value);
	boolean validateConnectionDsInitialContext(String value);
	boolean validateConnectionDsName(String value);
	boolean validateConnectionURL(String value);
	boolean validateConnectionUsername(String value);
	boolean validateConnectionPassword(String value);
	boolean validatePropertyAutocommit(SqlExecutorBooleanValue value);
	boolean validatePropertyIsolation(SqlExecutorIsolationLevel value);
	boolean validatePropertyMaxactive(int value);
	boolean validatePropertyMaxidle(int value);
	boolean validatePropertyMaxopenstatements(int value);
	boolean validatePropertyMaxwait(int value);
	boolean validatePropertyMinidle(int value);
	boolean validatePropertyPoolstatements(SqlExecutorBooleanValue value);
	boolean validatePropertyTestonborrow(SqlExecutorBooleanValue value);
	boolean validatePropertyTestwhileidle(SqlExecutorBooleanValue value);
	boolean validatePropertyValidationquery(String value);
	boolean validatePropertyInitialsize(int value);
	boolean validateSqlStatements(EList<SqlStatement> value);
}
