/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.EndPoint;
import org.wso2.developerstudio.eclipse.gmf.esb.MediatorSequence;
import org.wso2.developerstudio.eclipse.gmf.esb.RegistryKeyProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.TargetEndpointType;
import org.wso2.developerstudio.eclipse.gmf.esb.TargetSequenceType;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.AbstractCommonTarget}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractCommonTargetValidator {
	boolean validate();

	boolean validateSequenceType(TargetSequenceType value);
	boolean validateSequence(MediatorSequence value);
	boolean validateSequenceKey(RegistryKeyProperty value);
	boolean validateEndpointType(TargetEndpointType value);
	boolean validateEndpoint(EndPoint value);
	boolean validateEndpointKey(RegistryKeyProperty value);
}
