/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.AttributeType;
import org.wso2.developerstudio.eclipse.gmf.esb.AttributeValueType;
import org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.AbstractNameValueExpressionAttribute}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractNameValueExpressionAttributeValidator {
	boolean validate();

	boolean validateAttributeName(String value);
	boolean validateAttributeValueType(AttributeValueType value);
	boolean validateAttributeValue(String value);
	boolean validateAttributeType(AttributeType value);
	boolean validateAttributeExpression(NamespacedProperty value);
}
