/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.AggregateMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.AggregateMediatorOnCompleteOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.AggregateMediatorOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.AggregateSequenceType;
import org.wso2.developerstudio.eclipse.gmf.esb.CompletionMessagesType;
import org.wso2.developerstudio.eclipse.gmf.esb.MediatorFlow;
import org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.RegistryKeyProperty;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.AggregateMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AggregateMediatorValidator {
	boolean validate();

	boolean validateAggregateID(String value);
	boolean validateCorrelationExpression(NamespacedProperty value);
	boolean validateCompletionTimeout(long value);
	boolean validateCompletionMinMessagesType(CompletionMessagesType value);
	boolean validateCompletionMaxMessagesType(CompletionMessagesType value);
	boolean validateCompletionMinMessagesValue(int value);
	boolean validateCompletionMinMessagesExpression(NamespacedProperty value);
	boolean validateCompletionMaxMessagesValue(int value);
	boolean validateCompletionMaxMessagesExpression(NamespacedProperty value);
	boolean validateInputConnector(AggregateMediatorInputConnector value);
	boolean validateOutputConnector(AggregateMediatorOutputConnector value);
	boolean validateOnCompleteOutputConnector(AggregateMediatorOnCompleteOutputConnector value);
	boolean validateMediatorFlow(MediatorFlow value);
	boolean validateAggregationExpression(NamespacedProperty value);
	boolean validateSequenceType(AggregateSequenceType value);
	boolean validateSequenceKey(RegistryKeyProperty value);
	boolean validateEnclosingElementProperty(String value);
}
