/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.APIResourceFaultInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.APIResourceInSequenceInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.APIResourceInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.APIResourceOutSequenceOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.APIResourceOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.ApiResourceUrlStyle;
import org.wso2.developerstudio.eclipse.gmf.esb.Protocol;
import org.wso2.developerstudio.eclipse.gmf.esb.ProxyServiceContainer;
import org.wso2.developerstudio.eclipse.gmf.esb.RegistryKeyProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.SequenceType;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.APIResource}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface APIResourceValidator {
	boolean validate();

	boolean validateInputConnector(APIResourceInputConnector value);
	boolean validateOutputConnector(APIResourceOutputConnector value);
	boolean validateOutSequenceOutputConnector(APIResourceOutSequenceOutputConnector value);
	boolean validateInSequenceInputConnectors(EList<APIResourceInSequenceInputConnector> value);
	boolean validateFaultInputConnector(APIResourceFaultInputConnector value);
	boolean validateUrlStyle(ApiResourceUrlStyle value);
	boolean validateUriTemplate(String value);
	boolean validateUrlMapping(String value);
	boolean validateAllowGet(boolean value);
	boolean validateAllowPost(boolean value);
	boolean validateAllowPut(boolean value);
	boolean validateAllowDelete(boolean value);
	boolean validateAllowOptions(boolean value);
	boolean validateAllowHead(boolean value);
	boolean validateAllowPatch(boolean value);
	boolean validateContainer(ProxyServiceContainer value);
	boolean validateInSequenceType(SequenceType value);
	boolean validateInSequenceKey(RegistryKeyProperty value);
	boolean validateInSequenceName(String value);
	boolean validateOutSequenceType(SequenceType value);
	boolean validateOutSequenceKey(RegistryKeyProperty value);
	boolean validateOutSequenceName(String value);
	boolean validateFaultSequenceType(SequenceType value);
	boolean validateFaultSequenceKey(RegistryKeyProperty value);
	boolean validateFaultSequenceName(String value);
	boolean validateProtocol(Protocol value);
}
