/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.BeanMediatorAction;
import org.wso2.developerstudio.eclipse.gmf.esb.BeanMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.BeanMediatorOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.PropertyValueType;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.BeanMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BeanMediatorValidator {
	boolean validate();

	boolean validateInputConnector(BeanMediatorInputConnector value);
	boolean validateOutputConnector(BeanMediatorOutputConnector value);
	boolean validateClass(String value);
	boolean validateAction(BeanMediatorAction value);
	boolean validateVar(String value);
	boolean validateProperty(String value);
	boolean validateValueType(PropertyValueType value);
	boolean validateValueLiteral(String value);
	boolean validateValueExpression(NamespacedProperty value);
	boolean validateTargetType(PropertyValueType value);
	boolean validateTargetLiteral(String value);
	boolean validateTargetExpression(NamespacedProperty value);
}
