/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;


/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.CacheHttpMethods}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CacheHttpMethodsValidator {
	boolean validate();

	boolean validateGET(boolean value);
	boolean validatePOST(boolean value);
	boolean validatePUT(boolean value);
	boolean validateDELETE(boolean value);
	boolean validateHEAD(boolean value);
	boolean validateCONNECT(boolean value);
	boolean validateOPTIONS(boolean value);
	boolean validateTRACE(boolean value);
	boolean validatePATCH(boolean value);
}
