/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.CallMediatorEndpointOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.CallMediatorEndpointType;
import org.wso2.developerstudio.eclipse.gmf.esb.CallMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.CallMediatorOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.EndPoint;
import org.wso2.developerstudio.eclipse.gmf.esb.MediatorFlow;
import org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.RegistryKeyProperty;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.CallMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CallMediatorValidator {
	boolean validate();

	boolean validateInputConnector(CallMediatorInputConnector value);
	boolean validateOutputConnector(CallMediatorOutputConnector value);
	boolean validateEndpoint(EList<EndPoint> value);
	boolean validateEndpointOutputConnector(CallMediatorEndpointOutputConnector value);
	boolean validateMediatorFlow(MediatorFlow value);
	boolean validateEndpointType(CallMediatorEndpointType value);
	boolean validateEnableBlockingCalls(boolean value);
	boolean validateEndpointRegistrykey(RegistryKeyProperty value);
	boolean validateEndpointXpath(NamespacedProperty value);
}
