/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.CalloutEndpointType;
import org.wso2.developerstudio.eclipse.gmf.esb.CalloutMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.CalloutMediatorOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.CalloutPayloadType;
import org.wso2.developerstudio.eclipse.gmf.esb.CalloutResultType;
import org.wso2.developerstudio.eclipse.gmf.esb.CalloutSecurityPolicies;
import org.wso2.developerstudio.eclipse.gmf.esb.CalloutSecurityType;
import org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.RegistryKeyProperty;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.CalloutMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CalloutMediatorValidator {
	boolean validate();

	boolean validateServiceURL(String value);
	boolean validateSoapAction(String value);
	boolean validatePathToAxis2xml(String value);
	boolean validatePathToAxis2Repository(String value);
	boolean validatePayloadType(CalloutPayloadType value);
	boolean validatePayloadMessageXpath(NamespacedProperty value);
	boolean validateResultType(CalloutResultType value);
	boolean validateResultMessageXpath(NamespacedProperty value);
	boolean validateResultContextProperty(String value);
	boolean validatePassHeaders(boolean value);
	boolean validateInputConnector(CalloutMediatorInputConnector value);
	boolean validateOutputConnector(CalloutMediatorOutputConnector value);
	boolean validateAddressEndpoint(RegistryKeyProperty value);
	boolean validateEndpointType(CalloutEndpointType value);
	boolean validatePayloadProperty(String value);
	boolean validateSecurityType(CalloutSecurityType value);
	boolean validateOutboundPolicyKey(RegistryKeyProperty value);
	boolean validateInboundPolicyKey(RegistryKeyProperty value);
	boolean validatePolicies(CalloutSecurityPolicies value);
	boolean validatePolicyKey(RegistryKeyProperty value);
	boolean validateInitAxis2ClientOptions(boolean value);
}
