/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.CallTemplateMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.CallTemplateMediatorOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.CallTemplateParameter;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.CallTemplateMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CallTemplateMediatorValidator {
	boolean validate();

	boolean validateAvailableTemplates(String value);
	boolean validateTemplateParameters(EList<CallTemplateParameter> value);
	boolean validateInputConnector(CallTemplateMediatorInputConnector value);
	boolean validateOutputConnector(CallTemplateMediatorOutputConnector value);
	boolean validateTargetTemplate(String value);
}
