/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.CloneMediatorContainer;
import org.wso2.developerstudio.eclipse.gmf.esb.CloneMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.CloneMediatorOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.CloneMediatorTargetOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.CloneTarget;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.CloneMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CloneMediatorValidator {
	boolean validate();

	boolean validateCloneID(String value);
	boolean validateSequentialMediation(boolean value);
	boolean validateContinueParent(boolean value);
	boolean validateTargets(EList<CloneTarget> value);
	boolean validateTargetsOutputConnector(EList<CloneMediatorTargetOutputConnector> value);
	boolean validateInputConnector(CloneMediatorInputConnector value);
	boolean validateOutputConnector(CloneMediatorOutputConnector value);
	boolean validateCloneContainer(CloneMediatorContainer value);
}
