/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.CommandPropertyContextAction;
import org.wso2.developerstudio.eclipse.gmf.esb.CommandPropertyMessageAction;
import org.wso2.developerstudio.eclipse.gmf.esb.CommandPropertyValueType;
import org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.CommandProperty}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CommandPropertyValidator {
	boolean validate();

	boolean validatePropertyName(String value);
	boolean validateValueType(CommandPropertyValueType value);
	boolean validateValueLiteral(String value);
	boolean validateValueContextPropertyName(String value);
	boolean validateValueMessageElementXpath(NamespacedProperty value);
	boolean validateContextAction(CommandPropertyContextAction value);
	boolean validateMessageAction(CommandPropertyMessageAction value);
}
