/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.DataMapperMediatorDataTypes;
import org.wso2.developerstudio.eclipse.gmf.esb.DataMapperMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.DataMapperMediatorOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.RegistryKeyProperty;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.DataMapperMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataMapperMediatorValidator {
	boolean validate();

	boolean validateInputConnector(DataMapperMediatorInputConnector value);
	boolean validateInputType(DataMapperMediatorDataTypes value);
	boolean validateOutputConnector(DataMapperMediatorOutputConnector value);
	boolean validateConfiguration(RegistryKeyProperty value);
	boolean validateInputSchema(RegistryKeyProperty value);
	boolean validateOutputSchema(RegistryKeyProperty value);
	boolean validateConfigurationLocalPath(String value);
	boolean validateInputSchemaLocalPath(String value);
	boolean validateOutputSchemaLocalPath(String value);
	boolean validateOutputType(DataMapperMediatorDataTypes value);
}
