/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.EndPointProperty;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.EndPoint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EndPointValidator {
	boolean validate();

	boolean validateEndPointName(String value);
	boolean validateAnonymous(boolean value);
	boolean validateInLine(boolean value);
	boolean validateDuplicate(boolean value);
	boolean validateProperties(EList<EndPointProperty> value);
	boolean validateReversed(boolean value);
}
