/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.EntitlementCallbackHandler;
import org.wso2.developerstudio.eclipse.gmf.esb.EntitlementClientType;
import org.wso2.developerstudio.eclipse.gmf.esb.EntitlementContainer;
import org.wso2.developerstudio.eclipse.gmf.esb.EntitlementMediatorAdviceOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.EntitlementMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.EntitlementMediatorObligationsOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.EntitlementMediatorOnAcceptOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.EntitlementMediatorOnRejectOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.EntitlementMediatorOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.EntitlementSequenceType;
import org.wso2.developerstudio.eclipse.gmf.esb.RegistryKeyProperty;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.EntitlementMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EntitlementMediatorValidator {
	boolean validate();

	boolean validateEntitlementServerURL(String value);
	boolean validateUsername(String value);
	boolean validatePassword(String value);
	boolean validateCallbackClassName(String value);
	boolean validateThriftHost(String value);
	boolean validateThriftPort(String value);
	boolean validateEntitlementClientType(EntitlementClientType value);
	boolean validateOnRejectSequenceType(EntitlementSequenceType value);
	boolean validateOnAcceptSequenceType(EntitlementSequenceType value);
	boolean validateAdviceSequenceType(EntitlementSequenceType value);
	boolean validateObligationsSequenceType(EntitlementSequenceType value);
	boolean validateOnRejectSequenceKey(RegistryKeyProperty value);
	boolean validateOnAcceptSequenceKey(RegistryKeyProperty value);
	boolean validateAdviceSequenceKey(RegistryKeyProperty value);
	boolean validateObligationsSequenceKey(RegistryKeyProperty value);
	boolean validateEntitlementContainer(EntitlementContainer value);
	boolean validateInputConnector(EntitlementMediatorInputConnector value);
	boolean validateOutputConnector(EntitlementMediatorOutputConnector value);
	boolean validateOnRejectOutputConnector(EntitlementMediatorOnRejectOutputConnector value);
	boolean validateOnAcceptOutputConnector(EntitlementMediatorOnAcceptOutputConnector value);
	boolean validateAdviceOutputConnector(EntitlementMediatorAdviceOutputConnector value);
	boolean validateObligationsOutputConnector(EntitlementMediatorObligationsOutputConnector value);
	boolean validateCallbackHandler(EntitlementCallbackHandler value);
}
