/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.EsbSequenceInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.EsbSequenceOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.Mediator;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.EsbSequence}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EsbSequenceValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateInput(EsbSequenceInputConnector value);
	boolean validateOutput(EsbSequenceOutputConnector value);
	boolean validateChildMediators(EList<Mediator> value);
}
