/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.ArtifactType;
import org.wso2.developerstudio.eclipse.gmf.esb.EsbElement;
import org.wso2.developerstudio.eclipse.gmf.esb.MessageMediator;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.EsbServer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EsbServerValidator {
	boolean validate();

	boolean validateChildren(EList<EsbElement> value);
	boolean validateMessageMediator(MessageMediator value);
	boolean validateType(ArtifactType value);
}
