/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.EventMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.EventMediatorOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.EventTopicType;
import org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.EventMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EventMediatorValidator {
	boolean validate();

	boolean validateTopicType(EventTopicType value);
	boolean validateStaticTopic(String value);
	boolean validateDynamicTopic(NamespacedProperty value);
	boolean validateEventExpression(NamespacedProperty value);
	boolean validateInputConnector(EventMediatorInputConnector value);
	boolean validateOutputConnector(EventMediatorOutputConnector value);
}
