/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.FailoverEndPointInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.FailoverEndPointOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.FailoverEndPointWestOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.MediatorFlow;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.FailoverEndPoint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FailoverEndPointValidator {
	boolean validate();

	boolean validateInputConnector(FailoverEndPointInputConnector value);
	boolean validateOutputConnector(EList<FailoverEndPointOutputConnector> value);
	boolean validateWestOutputConnector(FailoverEndPointWestOutputConnector value);
	boolean validateMediatorFlow(MediatorFlow value);
}
