/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.FastXSLTMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.FastXSLTMediatorOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.KeyType;
import org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.RegistryKeyProperty;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.FastXSLTMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FastXSLTMediatorValidator {
	boolean validate();

	boolean validateFastXsltSchemaKeyType(KeyType value);
	boolean validateFastXsltStaticSchemaKey(RegistryKeyProperty value);
	boolean validateFastXsltDynamicSchemaKey(NamespacedProperty value);
	boolean validateInputConnector(FastXSLTMediatorInputConnector value);
	boolean validateOutputConnector(FastXSLTMediatorOutputConnector value);
}
