/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.FaultCodeSoap11;
import org.wso2.developerstudio.eclipse.gmf.esb.FaultCodeSoap12;
import org.wso2.developerstudio.eclipse.gmf.esb.FaultCodeType;
import org.wso2.developerstudio.eclipse.gmf.esb.FaultDetailType;
import org.wso2.developerstudio.eclipse.gmf.esb.FaultMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.FaultMediatorOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.FaultReasonType;
import org.wso2.developerstudio.eclipse.gmf.esb.FaultSoapVersion;
import org.wso2.developerstudio.eclipse.gmf.esb.FaultStringType;
import org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.FaultMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FaultMediatorValidator {
	boolean validate();

	boolean validateSoapVersion(FaultSoapVersion value);
	boolean validateSerializeResponse(boolean value);
	boolean validateMarkAsResponse(boolean value);
	boolean validateFaultCodeSoap11(FaultCodeSoap11 value);
	boolean validateFaultCodeType(FaultCodeType value);
	boolean validateFaultCodeExpression(NamespacedProperty value);
	boolean validateFaultStringType(FaultStringType value);
	boolean validateFaultStringValue(String value);
	boolean validateFaultStringExpression(NamespacedProperty value);
	boolean validateFaultActor(String value);
	boolean validateFaultCodeSoap12(FaultCodeSoap12 value);
	boolean validateFaultReasonType(FaultReasonType value);
	boolean validateFaultReasonValue(String value);
	boolean validateFaultReasonExpression(NamespacedProperty value);
	boolean validateRoleName(String value);
	boolean validateNodeName(String value);
	boolean validateFaultDetailType(FaultDetailType value);
	boolean validateFaultDetailValue(String value);
	boolean validateFaultDetailExpression(NamespacedProperty value);
	boolean validateInputConnector(FaultMediatorInputConnector value);
	boolean validateOutputConnector(FaultMediatorOutputConnector value);
}
