/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.IterateMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.IterateMediatorOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.IterateMediatorTargetOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.IterateTarget;
import org.wso2.developerstudio.eclipse.gmf.esb.MediatorFlow;
import org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.RegistryKeyProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.SequenceType;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.IterateMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IterateMediatorValidator {
	boolean validate();

	boolean validateIterateID(String value);
	boolean validateSequentialMediation(boolean value);
	boolean validateContinueParent(boolean value);
	boolean validatePreservePayload(boolean value);
	boolean validateIterateExpression(NamespacedProperty value);
	boolean validateAttachPath(NamespacedProperty value);
	boolean validateTarget(IterateTarget value);
	boolean validateInputConnector(IterateMediatorInputConnector value);
	boolean validateOutputConnector(IterateMediatorOutputConnector value);
	boolean validateTargetOutputConnector(IterateMediatorTargetOutputConnector value);
	boolean validateMediatorFlow(MediatorFlow value);
	boolean validateSequenceType(SequenceType value);
	boolean validateSequenceKey(RegistryKeyProperty value);
	boolean validateSequenceName(String value);
}
