/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.LoadBalanceEndPointInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.LoadBalanceEndPointOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.LoadBalanceEndPointWestOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.LoadBalanceSessionType;
import org.wso2.developerstudio.eclipse.gmf.esb.MediatorFlow;
import org.wso2.developerstudio.eclipse.gmf.esb.Member;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.LoadBalanceEndPoint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LoadBalanceEndPointValidator {
	boolean validate();

	boolean validateFailover(boolean value);
	boolean validatePolicy(String value);
	boolean validateInputConnector(LoadBalanceEndPointInputConnector value);
	boolean validateOutputConnector(EList<LoadBalanceEndPointOutputConnector> value);
	boolean validateWestOutputConnector(LoadBalanceEndPointWestOutputConnector value);
	boolean validateMember(EList<Member> value);
	boolean validateSessionType(LoadBalanceSessionType value);
	boolean validateAlgorithm(String value);
	boolean validateSessionTimeout(long value);
	boolean validateMediatorFlow(MediatorFlow value);
}
