/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.LocalEntryValueType;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.LocalEntry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LocalEntryValidator {
	boolean validate();

	boolean validateEntryName(String value);
	boolean validateLocalEntryType(LocalEntryValueType value);
	boolean validateValueLiteral(String value);
	boolean validateValueXML(String value);
	boolean validateValueURL(String value);
}
