/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.JDBCConnectionInformationType;
import org.wso2.developerstudio.eclipse.gmf.esb.JMSSpecVersion;
import org.wso2.developerstudio.eclipse.gmf.esb.MessageStoreParameter;
import org.wso2.developerstudio.eclipse.gmf.esb.MessageStoreType;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.MessageStore}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MessageStoreValidator {
	boolean validate();

	boolean validateStoreName(String value);
	boolean validateStoreType(MessageStoreType value);
	boolean validateInitialContextFactory(String value);
	boolean validateProviderURL(String value);
	boolean validateJndiQueueName(String value);
	boolean validateConnectionFactory(String value);
	boolean validateUserName(String value);
	boolean validatePassword(String value);
	boolean validateCacheConnection(boolean value);
	boolean validateJmsSpecVersion(JMSSpecVersion value);
	boolean validateEnableCaching(boolean value);
	boolean validateProviderClass(String value);
	boolean validateRabbitMQServerHostName(String value);
	boolean validateRabbitMQServerHostPort(String value);
	boolean validateRabbitMQQueueName(String value);
	boolean validateRabbitMQExchangeName(String value);
	boolean validateRoutingKey(String value);
	boolean validateRabbitMQUserName(String value);
	boolean validateRabbitMQPassword(String value);
	boolean validateVirtualHost(String value);
	boolean validateJdbcDatabaseTable(String value);
	boolean validateJdbcConnectionInformation(JDBCConnectionInformationType value);
	boolean validateJdbcDriver(String value);
	boolean validateJdbcURL(String value);
	boolean validateJdbcUser(String value);
	boolean validateJdbcPassword(String value);
	boolean validateJdbcDatasourceName(String value);
	boolean validateParameters(EList<MessageStoreParameter> value);
	boolean validateEnableProducerGuaranteedDelivery(boolean value);
	boolean validateFailoverMessageStore(String value);
}
