/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import java.util.Map;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NamespacedPropertyValidator {
	boolean validate();

	boolean validatePrettyName(String value);
	boolean validatePropertyName(String value);
	boolean validatePropertyValue(String value);
	boolean validateNamespaces(Map<String, String> value);
	boolean validateSupportsDynamicXPaths(boolean value);
	boolean validateDynamic(boolean value);
}
