/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.MediaType;
import org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.PayloadFactoryArgumentType;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.PayloadFactoryArgument}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PayloadFactoryArgumentValidator {
	boolean validate();

	boolean validateArgumentType(PayloadFactoryArgumentType value);
	boolean validateArgumentValue(String value);
	boolean validateArgumentExpression(NamespacedProperty value);
	boolean validateEvaluator(MediaType value);
	boolean validateLiteral(boolean value);
}
