/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.ProxyServiceFaultContainer;
import org.wso2.developerstudio.eclipse.gmf.esb.ProxyServiceSequenceAndEndpointContainer;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.ProxyServiceContainer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProxyServiceContainerValidator {
	boolean validate();

	boolean validateSequenceAndEndpointContainer(ProxyServiceSequenceAndEndpointContainer value);
	boolean validateFaultContainer(ProxyServiceFaultContainer value);
}
