/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.ProxyFaultInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.ProxyInSequenceInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.ProxyInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.ProxyOutSequenceOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.ProxyOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.ProxyServiceContainer;
import org.wso2.developerstudio.eclipse.gmf.esb.ProxyServiceParameter;
import org.wso2.developerstudio.eclipse.gmf.esb.ProxyServicePolicy;
import org.wso2.developerstudio.eclipse.gmf.esb.ProxyWSDLResource;
import org.wso2.developerstudio.eclipse.gmf.esb.ProxyWsdlType;
import org.wso2.developerstudio.eclipse.gmf.esb.RegistryKeyProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.SequenceType;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.ProxyService}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProxyServiceValidator {
	boolean validate();

	boolean validateOutputConnector(ProxyOutputConnector value);
	boolean validateInputConnector(ProxyInputConnector value);
	boolean validateFaultInputConnector(ProxyFaultInputConnector value);
	boolean validateOutSequenceOutputConnector(ProxyOutSequenceOutputConnector value);
	boolean validateInSequenceInputConnectors(EList<ProxyInSequenceInputConnector> value);
	boolean validateName(String value);
	boolean validatePinnedServers(String value);
	boolean validateServiceGroup(String value);
	boolean validateTraceEnabled(boolean value);
	boolean validateStatisticsEnabled(boolean value);
	boolean validateStartOnLoad(boolean value);
	boolean validateTransports(String value);
	boolean validateReliableMessagingEnabled(boolean value);
	boolean validateSecurityEnabled(boolean value);
	boolean validateServiceParameters(EList<ProxyServiceParameter> value);
	boolean validateServicePolicies(EList<ProxyServicePolicy> value);
	boolean validateContainer(ProxyServiceContainer value);
	boolean validateInSequenceType(SequenceType value);
	boolean validateInSequenceKey(RegistryKeyProperty value);
	boolean validateInSequenceName(String value);
	boolean validateInSequenceOnError(RegistryKeyProperty value);
	boolean validateOutSequenceType(SequenceType value);
	boolean validateOutSequenceKey(RegistryKeyProperty value);
	boolean validateOutSequenceName(String value);
	boolean validateOutSequenceOnError(RegistryKeyProperty value);
	boolean validateFaultSequenceType(SequenceType value);
	boolean validateFaultSequenceKey(RegistryKeyProperty value);
	boolean validateFaultSequenceName(String value);
	boolean validateFaultSequenceOnError(RegistryKeyProperty value);
	boolean validateEndpointType(SequenceType value);
	boolean validateEndpointKey(RegistryKeyProperty value);
	boolean validateEndpointName(String value);
	boolean validateMainSequence(boolean value);
	boolean validateWsdlType(ProxyWsdlType value);
	boolean validateWsdlXML(String value);
	boolean validateWsdlURL(String value);
	boolean validateWsdlKey(RegistryKeyProperty value);
	boolean validateWsdlEndpoint(RegistryKeyProperty value);
	boolean validateWsdlResources(EList<ProxyWSDLResource> value);
	boolean validateOnError(RegistryKeyProperty value);
}
