/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.PublishEventMediatorAttribute;
import org.wso2.developerstudio.eclipse.gmf.esb.PublishEventMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.PublishEventMediatorOutputConnector;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.PublishEventMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PublishEventMediatorValidator {
	boolean validate();

	boolean validateInputConnector(PublishEventMediatorInputConnector value);
	boolean validateOutputconnector(PublishEventMediatorOutputConnector value);
	boolean validateStreamName(String value);
	boolean validateStreamVersion(String value);
	boolean validateEventSink(String value);
	boolean validateMetaAttributes(EList<PublishEventMediatorAttribute> value);
	boolean validateCorrelationAttributes(EList<PublishEventMediatorAttribute> value);
	boolean validatePayloadAttributes(EList<PublishEventMediatorAttribute> value);
	boolean validateArbitraryAttributes(EList<PublishEventMediatorAttribute> value);
}
