/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.MediatorFlow;
import org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.RecipientListEndPointInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.RecipientListEndPointOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.RecipientListEndPointWestOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.RecipientListEndpointType;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.RecipientListEndPoint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RecipientListEndPointValidator {
	boolean validate();

	boolean validateInputConnector(RecipientListEndPointInputConnector value);
	boolean validateOutputConnector(EList<RecipientListEndPointOutputConnector> value);
	boolean validateWestOutputConnector(RecipientListEndPointWestOutputConnector value);
	boolean validateEndpointType(RecipientListEndpointType value);
	boolean validateEndpointsValue(String value);
	boolean validateEndpointsExpression(NamespacedProperty value);
	boolean validateMaxCache(int value);
	boolean validateMediatorFlow(MediatorFlow value);
}
