/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.RMSequenceMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.RMSequenceMediatorOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.RMSequenceType;
import org.wso2.developerstudio.eclipse.gmf.esb.RMSpecVersion;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.RMSequenceMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RMSequenceMediatorValidator {
	boolean validate();

	boolean validateRmSpecVersion(RMSpecVersion value);
	boolean validateSequenceType(RMSequenceType value);
	boolean validateCorrelationXpath(NamespacedProperty value);
	boolean validateLastMessageXpath(NamespacedProperty value);
	boolean validateInputConnector(RMSequenceMediatorInputConnector value);
	boolean validateOutputConnector(RMSequenceMediatorOutputConnector value);
}
