/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.RegistryKeyProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.RuleResultType;
import org.wso2.developerstudio.eclipse.gmf.esb.RuleResultValueType;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.RuleResult}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RuleResultValidator {
	boolean validate();

	boolean validateResultType(RuleResultType value);
	boolean validateResultCustomType(String value);
	boolean validateResultName(String value);
	boolean validateValueType(RuleResultValueType value);
	boolean validateValueLiteral(String value);
	boolean validateValueExpression(NamespacedProperty value);
	boolean validateValueKey(RegistryKeyProperty value);
}
