/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.RegistryKeyProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.RuleFactType;
import org.wso2.developerstudio.eclipse.gmf.esb.RuleFactValueType;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.RuleFact}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RuleFactValidator {
	boolean validate();

	boolean validateFactType(RuleFactType value);
	boolean validateFactCustomType(String value);
	boolean validateFactName(String value);
	boolean validateValueType(RuleFactValueType value);
	boolean validateValueLiteral(String value);
	boolean validateValueExpression(NamespacedProperty value);
	boolean validateValueKey(RegistryKeyProperty value);
}
