/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.MediatorFlow;
import org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.RegistryKeyProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.RuleActions;
import org.wso2.developerstudio.eclipse.gmf.esb.RuleChildMediatorsConfiguration;
import org.wso2.developerstudio.eclipse.gmf.esb.RuleFactsConfiguration;
import org.wso2.developerstudio.eclipse.gmf.esb.RuleMediatorChildMediatorsOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.RuleMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.RuleMediatorOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.RuleResultsConfiguration;
import org.wso2.developerstudio.eclipse.gmf.esb.RuleSessionProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.RuleSourceType;
import org.wso2.developerstudio.eclipse.gmf.esb.RuleType;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.RuleMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RuleMediatorValidator {
	boolean validate();

	boolean validateRuleSetURL(String value);
	boolean validateRuleSetSourceType(RuleSourceType value);
	boolean validateRuleSetSourceCode(String value);
	boolean validateRuleSetSourceKey(RegistryKeyProperty value);
	boolean validateStatefulSession(boolean value);
	boolean validateRuleSessionProperties(EList<RuleSessionProperty> value);
	boolean validateFactsConfiguration(RuleFactsConfiguration value);
	boolean validateResultsConfiguration(RuleResultsConfiguration value);
	boolean validateChildMediatorsConfiguration(RuleChildMediatorsConfiguration value);
	boolean validateInputConnector(RuleMediatorInputConnector value);
	boolean validateOutputConnector(RuleMediatorOutputConnector value);
	boolean validateChildMediatorsOutputConnector(RuleMediatorChildMediatorsOutputConnector value);
	boolean validateMediatorFlow(MediatorFlow value);
	boolean validateSourceValue(String value);
	boolean validateSourceXpath(NamespacedProperty value);
	boolean validateTargetValue(String value);
	boolean validateTargetResultXpath(NamespacedProperty value);
	boolean validateTargetXpath(NamespacedProperty value);
	boolean validateTargetAction(RuleActions value);
	boolean validateInputWrapperName(String value);
	boolean validateInputNameSpace(String value);
	boolean validateOutputWrapperName(String value);
	boolean validateOutputNameSpace(String value);
	boolean validateRuleSetType(RuleType value);
}
