/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.ExpressionAction;
import org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.OutputMethod;
import org.wso2.developerstudio.eclipse.gmf.esb.RegistryKeyProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.SmooksIODataType;
import org.wso2.developerstudio.eclipse.gmf.esb.SmooksMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.SmooksMediatorOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.SmooksOutputDataType;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.SmooksMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SmooksMediatorValidator {
	boolean validate();

	boolean validateConfigurationKey(RegistryKeyProperty value);
	boolean validateInputType(SmooksIODataType value);
	boolean validateInputExpression(NamespacedProperty value);
	boolean validateOutputType(SmooksOutputDataType value);
	boolean validateOutputExpression(NamespacedProperty value);
	boolean validateOutputProperty(String value);
	boolean validateOutputAction(ExpressionAction value);
	boolean validateOutputMethod(OutputMethod value);
	boolean validateInputConnector(SmooksMediatorInputConnector value);
	boolean validateOutputConnector(SmooksMediatorOutputConnector value);
}
