/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.SqlParameterDataType;
import org.wso2.developerstudio.eclipse.gmf.esb.SqlParameterValueType;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.SqlParameterDefinition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SqlParameterDefinitionValidator {
	boolean validate();

	boolean validateDataType(SqlParameterDataType value);
	boolean validateValueType(SqlParameterValueType value);
	boolean validateValueLiteral(String value);
	boolean validateValueExpression(NamespacedProperty value);
}
