/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.SqlParameterDefinition;
import org.wso2.developerstudio.eclipse.gmf.esb.SqlResultMapping;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.SqlStatement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SqlStatementValidator {
	boolean validate();

	boolean validateQueryString(String value);
	boolean validateParameters(EList<SqlParameterDefinition> value);
	boolean validateResultsEnabled(boolean value);
	boolean validateResults(EList<SqlResultMapping> value);
}
