/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.RegistryKeyProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.StoreMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.StoreMediatorOutputConnector;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.StoreMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StoreMediatorValidator {
	boolean validate();

	boolean validateMessageStore(String value);
	boolean validateOnStoreSequence(RegistryKeyProperty value);
	boolean validateInputConnector(StoreMediatorInputConnector value);
	boolean validateOutputConnector(StoreMediatorOutputConnector value);
	boolean validateAvailableMessageStores(String value);
}
