/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.SwitchCaseBranchOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.SwitchDefaultBranchOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.SwitchMediatorContainer;
import org.wso2.developerstudio.eclipse.gmf.esb.SwitchMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.SwitchMediatorOutputConnector;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.SwitchMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SwitchMediatorValidator {
	boolean validate();

	boolean validateSourceXpath(NamespacedProperty value);
	boolean validateSource(String value);
	boolean validateNamespace(String value);
	boolean validateNamespacePrefix(String value);
	boolean validateCaseBranches(EList<SwitchCaseBranchOutputConnector> value);
	boolean validateDefaultBranch(SwitchDefaultBranchOutputConnector value);
	boolean validateInputConnector(SwitchMediatorInputConnector value);
	boolean validateOutputConnector(SwitchMediatorOutputConnector value);
	boolean validateSwitchContainer(SwitchMediatorContainer value);
}
