/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.TaskProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.TaskTriggerType;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.Task}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TaskValidator {
	boolean validate();

	boolean validateTaskName(String value);
	boolean validateTaskGroup(String value);
	boolean validateTriggerType(TaskTriggerType value);
	boolean validateCount(long value);
	boolean validateInterval(long value);
	boolean validateCron(String value);
	boolean validatePinnedServers(String value);
	boolean validateTaskImplementation(String value);
	boolean validateTaskProperties(EList<TaskProperty> value);
}
