/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.EsbElement;
import org.wso2.developerstudio.eclipse.gmf.esb.TemplateParameter;
import org.wso2.developerstudio.eclipse.gmf.esb.TemplateType;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.Template}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TemplateValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateTemplateType(TemplateType value);
	boolean validateChild(EsbElement value);
	boolean validateParameters(EList<TemplateParameter> value);
}
