/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.TemplateEndpointInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.TemplateEndpointOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.TemplateEndpointParameter;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.TemplateEndpoint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TemplateEndpointValidator {
	boolean validate();

	boolean validateInputConnector(TemplateEndpointInputConnector value);
	boolean validateOutputConnector(TemplateEndpointOutputConnector value);
	boolean validateAddress(String value);
	boolean validateTargetTemplate(String value);
	boolean validateParameters(EList<TemplateEndpointParameter> value);
	boolean validateAvailableTemplates(String value);
}
