/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.RegistryKeyProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.ThrottlePolicyEntry;
import org.wso2.developerstudio.eclipse.gmf.esb.ThrottlePolicyType;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.ThrottlePolicyConfiguration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ThrottlePolicyConfigurationValidator {
	boolean validate();

	boolean validatePolicyType(ThrottlePolicyType value);
	boolean validatePolicyKey(RegistryKeyProperty value);
	boolean validateMaxConcurrentAccessCount(int value);
	boolean validatePolicyEntries(EList<ThrottlePolicyEntry> value);
}
