/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.wso2.developerstudio.eclipse.gmf.esb.ThrottleAccessType;
import org.wso2.developerstudio.eclipse.gmf.esb.ThrottleConditionType;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.ThrottlePolicyEntry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ThrottlePolicyEntryValidator {
	boolean validate();

	boolean validateThrottleType(ThrottleConditionType value);
	boolean validateThrottleRange(String value);
	boolean validateAccessType(ThrottleAccessType value);
	boolean validateMaxRequestCount(int value);
	boolean validateUnitTime(int value);
	boolean validateProhibitPeriod(int value);
}
