/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.RegistryKeyProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.ThrottleContainer;
import org.wso2.developerstudio.eclipse.gmf.esb.ThrottleMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.ThrottleMediatorOnAcceptOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.ThrottleMediatorOnRejectOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.ThrottleMediatorOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.ThrottleOnAcceptBranch;
import org.wso2.developerstudio.eclipse.gmf.esb.ThrottleOnRejectBranch;
import org.wso2.developerstudio.eclipse.gmf.esb.ThrottlePolicyConfiguration;
import org.wso2.developerstudio.eclipse.gmf.esb.ThrottlePolicyEntry;
import org.wso2.developerstudio.eclipse.gmf.esb.ThrottlePolicyType;
import org.wso2.developerstudio.eclipse.gmf.esb.ThrottleSequenceType;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.ThrottleMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ThrottleMediatorValidator {
	boolean validate();

	boolean validateGroupId(String value);
	boolean validatePolicyType(ThrottlePolicyType value);
	boolean validatePolicyKey(RegistryKeyProperty value);
	boolean validateMaxConcurrentAccessCount(int value);
	boolean validatePolicyEntries(EList<ThrottlePolicyEntry> value);
	boolean validatePolicyConfiguration(ThrottlePolicyConfiguration value);
	boolean validateOnAcceptBranch(ThrottleOnAcceptBranch value);
	boolean validateOnRejectBranch(ThrottleOnRejectBranch value);
	boolean validateInputConnector(ThrottleMediatorInputConnector value);
	boolean validateOutputConnector(ThrottleMediatorOutputConnector value);
	boolean validateOnAcceptOutputConnector(ThrottleMediatorOnAcceptOutputConnector value);
	boolean validateOnRejectOutputConnector(ThrottleMediatorOnRejectOutputConnector value);
	boolean validateThrottleContainer(ThrottleContainer value);
	boolean validateOnAcceptBranchsequenceType(ThrottleSequenceType value);
	boolean validateOnAcceptBranchsequenceKey(RegistryKeyProperty value);
	boolean validateOnRejectBranchsequenceType(ThrottleSequenceType value);
	boolean validateOnRejectBranchsequenceKey(RegistryKeyProperty value);
}
