/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.URLRewriteMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.URLRewriteMediatorOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.URLRewriteRule;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.URLRewriteMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface URLRewriteMediatorValidator {
	boolean validate();

	boolean validateUrlRewriteRules(EList<URLRewriteRule> value);
	boolean validateInProperty(String value);
	boolean validateOutProperty(String value);
	boolean validateInputConnector(URLRewriteMediatorInputConnector value);
	boolean validateOutputConnector(URLRewriteMediatorOutputConnector value);
}
