/**
 *
 * $Id$
 */
package org.wso2.developerstudio.eclipse.gmf.esb.validation;

import org.eclipse.emf.common.util.EList;

import org.wso2.developerstudio.eclipse.gmf.esb.MediatorFlow;
import org.wso2.developerstudio.eclipse.gmf.esb.NamespacedProperty;
import org.wso2.developerstudio.eclipse.gmf.esb.ValidateFeature;
import org.wso2.developerstudio.eclipse.gmf.esb.ValidateMediatorInputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.ValidateMediatorOnFailOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.ValidateMediatorOutputConnector;
import org.wso2.developerstudio.eclipse.gmf.esb.ValidateResource;
import org.wso2.developerstudio.eclipse.gmf.esb.ValidateSchema;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.eclipse.gmf.esb.ValidateMediator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ValidateMediatorValidator {
	boolean validate();

	boolean validateSourceXpath(NamespacedProperty value);
	boolean validateFeatures(EList<ValidateFeature> value);
	boolean validateSchemas(EList<ValidateSchema> value);
	boolean validateInputConnector(ValidateMediatorInputConnector value);
	boolean validateOutputConnector(ValidateMediatorOutputConnector value);
	boolean validateOnFailOutputConnector(ValidateMediatorOnFailOutputConnector value);
	boolean validateMediatorFlow(MediatorFlow value);
	boolean validateResources(EList<ValidateResource> value);
}
